import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import card from './components/card.js'
import dynamic from 'next/dynamic'
const DynamicComponent = dynamic(() => import('./components/card.js'))

export default function Home() {
  return (
    <div className="px-3 mt-3">
      <Head>
        <title>Sample App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicComponent />
      <DynamicComponent />
    </div>
  )
}
